# Generated by Django 2.1.1 on 2019-07-18 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('davari', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='judgment',
            name='barandeh',
        ),
        migrations.RemoveField(
            model_name='judgment',
            name='suggest',
        ),
        migrations.DeleteModel(
            name='Judgment',
        ),
    ]
