# Generated by Django 2.1.1 on 2019-05-27 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mojodi', models.DecimalField(decimal_places=0, max_digits=10)),
                ('resume_description', models.TextField(max_length=500)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='FileGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('file', models.FileField(upload_to='media/upload/files')),
            ],
        ),
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Maharat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('mohlat_rooz', models.IntegerField(default=0)),
                ('mohlat_saat', models.IntegerField(default=0)),
                ('word_count', models.IntegerField()),
                ('zemanat_price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('content', models.TextField(blank=True)),
                ('file', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='business.FileGallery')),
                ('file_type', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='business.FileType')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Suggest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('zaman_pishnahadi', models.IntegerField()),
                ('mablagh_pishnahadi', models.DecimalField(decimal_places=0, max_digits=10)),
                ('description', models.TextField(blank=True, max_length=300)),
                ('score', models.IntegerField()),
                ('time_tahvil', models.DateTimeField(blank=True, null=True)),
                ('judgment_request', models.BooleanField()),
                ('judgment_description', models.TextField(blank=True, max_length=500)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='business.FileGallery')),
                ('file_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='business.FileType')),
                ('judgment_user_request', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_request', to=settings.AUTH_USER_MODEL)),
                ('mojri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Sentence')),
            ],
        ),
        migrations.CreateModel(
            name='SuggestStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Takhasos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='suggest',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='business.SuggestStatus'),
        ),
        migrations.AddField(
            model_name='sentence',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='business.Status'),
        ),
        migrations.AddField(
            model_name='sentence',
            name='takhasos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='business.Takhasos'),
        ),
        migrations.AddField(
            model_name='sentence',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='sentence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Sentence'),
        ),
        migrations.AddField(
            model_name='report',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='maharat',
            field=models.ManyToManyField(blank=True, to='business.Maharat'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='resume_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='business.FileGallery'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='user_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='business.UserStatus'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='user_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='business.UserType'),
        ),
    ]
