# Generated by Django 2.1.1 on 2019-07-22 02:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Judgment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('judgment_description', models.TextField(blank=True, max_length=500)),
                ('judgment_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('judgment_won_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='won_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SentenceStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='FileType',
            new_name='ContentType',
        ),
        migrations.AlterModelOptions(
            name='sentence',
            options={'ordering': ('-id',)},
        ),
        migrations.RenameField(
            model_name='suggest',
            old_name='time_tahvil',
            new_name='upload_time',
        ),
        migrations.RemoveField(
            model_name='sentence',
            name='content',
        ),
        migrations.RemoveField(
            model_name='sentence',
            name='file',
        ),
        migrations.RemoveField(
            model_name='sentence',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='suggest',
            name='file',
        ),
        migrations.RemoveField(
            model_name='suggest',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='suggest',
            name='judgment_description',
        ),
        migrations.RemoveField(
            model_name='suggest',
            name='judgment_request',
        ),
        migrations.RemoveField(
            model_name='suggest',
            name='judgment_user_request',
        ),
        migrations.RemoveField(
            model_name='suggest',
            name='score',
        ),
        migrations.RemoveField(
            model_name='suggest',
            name='zaman_pishnahadi',
        ),
        migrations.AddField(
            model_name='sentence',
            name='content_text',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sentence',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sentence',
            name='translator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='translator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='suggest',
            name='completeFile',
            field=models.FileField(null=True, upload_to='media/upload/Content_File_Of_Suggest'),
        ),
        migrations.AddField(
            model_name='suggest',
            name='rate_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='mohlat_rooz',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='business.SentenceStatus'),
        ),
        migrations.RenameModel(
            old_name='Status',
            new_name='JudgmentsStatus',
        ),
        migrations.AddField(
            model_name='judgment',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='business.JudgmentsStatus'),
        ),
        migrations.AddField(
            model_name='judgment',
            name='suggest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Suggest'),
        ),
    ]
