# Generated by Django 2.1.1 on 2019-06-28 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentsOfSuggest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_text', models.TextField()),
                ('content_file', models.FileField(upload_to='media/upload/Contents_Of_Suggest_Files')),
                ('judgment_request', models.BooleanField(null=True)),
                ('judgment_description', models.TextField(blank=True, max_length=500)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='sentence',
            options={'ordering': ('-id',)},
        ),
        migrations.RemoveField(
            model_name='sentence',
            name='content',
        ),
        migrations.RemoveField(
            model_name='sentence',
            name='file',
        ),
        migrations.RemoveField(
            model_name='sentence',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='suggest',
            name='file',
        ),
        migrations.RemoveField(
            model_name='suggest',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='suggest',
            name='judgment_description',
        ),
        migrations.RemoveField(
            model_name='suggest',
            name='judgment_request',
        ),
        migrations.RemoveField(
            model_name='suggest',
            name='judgment_user_request',
        ),
        migrations.RemoveField(
            model_name='suggest',
            name='score',
        ),
        migrations.RemoveField(
            model_name='suggest',
            name='time_tahvil',
        ),
        migrations.RemoveField(
            model_name='suggest',
            name='zaman_pishnahadi',
        ),
        migrations.AddField(
            model_name='sentence',
            name='content_text',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sentence',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sentence',
            name='mohlat_rooz',
            field=models.IntegerField(),
        ),
        migrations.RenameModel(
            old_name='FileType',
            new_name='ContentType',
        ),
        migrations.AddField(
            model_name='contentsofsuggest',
            name='content_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='business.ContentType'),
        ),
        migrations.AddField(
            model_name='contentsofsuggest',
            name='judgment_user_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_request', to=settings.AUTH_USER_MODEL),
        ),
    ]
