# Generated by Django 2.1.1 on 2019-05-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='mohlat_rooz',
            field=models.IntegerField(),
        ),
    ]
