# Generated by Django 2.1.1 on 2019-06-28 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_auto_20190628_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='content_text',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
