# Generated by Django 2.1.1 on 2019-07-22 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_auto_20190722_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judgment',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='business.JudgmentsStatus'),
        ),
    ]
