# Generated by Django 2.1.1 on 2019-07-31 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_auto_20190722_0706'),
    ]

    operations = [
        migrations.AddField(
            model_name='judgment',
            name='davar_description',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
