# Generated by Django 2.1.1 on 2019-06-28 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_auto_20190628_1712'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Status',
            new_name='SentenceStatus',
        ),
    ]
