# Generated by Django 2.1.1 on 2019-05-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_auto_20190527_2120'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FileType',
            new_name='ContentType',
        ),
        migrations.RenameField(
            model_name='sentence',
            old_name='content',
            new_name='content_text',
        ),
        migrations.RenameField(
            model_name='sentence',
            old_name='file_type',
            new_name='content_type',
        ),
        migrations.RenameField(
            model_name='suggest',
            old_name='file_type',
            new_name='content_type',
        ),
        migrations.RemoveField(
            model_name='sentence',
            name='file',
        ),
        migrations.RemoveField(
            model_name='suggest',
            name='file',
        ),
        migrations.AddField(
            model_name='sentence',
            name='content_file',
            field=models.FileField(null=True, upload_to='media/upload/sentence_files'),
        ),
        migrations.AddField(
            model_name='suggest',
            name='content_file',
            field=models.FileField(null=True, upload_to='media/upload/suggest_files'),
        ),
        migrations.AddField(
            model_name='suggest',
            name='content_text',
            field=models.TextField(blank=True),
        ),
    ]
