# Generated by Django 2.1.1 on 2019-05-31 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_auto_20190527_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentence',
            name='content_file',
        ),
        migrations.RemoveField(
            model_name='sentence',
            name='content_type',
        ),
        migrations.AlterField(
            model_name='sentence',
            name='content_text',
            field=models.TextField(max_length=500),
        ),
    ]
