# Generated by Django 2.1.1 on 2019-06-15 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_auto_20190531_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggest',
            name='zaman_pishnahadi',
        ),
    ]
