# Generated by Django 2.1.1 on 2019-08-02 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_auto_20190802_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='payment_status',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='business.PaymentStatus'),
        ),
    ]
