# Generated by Django 2.1.1 on 2019-07-18 02:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0005_sentence_translator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Judgment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('judgment_description', models.TextField(blank=True, max_length=500)),
                ('judgment_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('judgment_won_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='won_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='contentsofsuggest',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='contentsofsuggest',
            name='judgment_user_request',
        ),
        migrations.AddField(
            model_name='suggest',
            name='completeFile',
            field=models.FileField(blank=True, null=True, upload_to='media/upload/Content_File_Of_Suggest'),
        ),
        migrations.AddField(
            model_name='suggest',
            name='rate_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.DeleteModel(
            name='ContentsOfSuggest',
        ),
        migrations.AddField(
            model_name='judgment',
            name='suggest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Suggest'),
        ),
    ]
