# Generated by Django 2.1.1 on 2019-07-19 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_auto_20190718_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggest',
            name='upload_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
