# Generated by Django 2.1.1 on 2019-08-14 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_auto_20190802_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='maharat',
        ),
    ]
