# Generated by Django 2.1.1 on 2019-06-15 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_remove_suggest_zaman_pishnahadi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggest',
            name='score',
            field=models.IntegerField(null=True),
        ),
    ]
