# Generated by Django 2.1.1 on 2019-06-19 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_auto_20190615_0650'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='title',
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
