# Generated by Django 2.1.1 on 2019-06-19 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_sentence_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
