# Generated by Django 2.1.1 on 2019-08-18 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_auto_20190814_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='resume_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='business.FileGallery'),
        ),
    ]
