# Generated by Django 2.1.1 on 2019-09-24 05:02

from django.db import migrations


def seed_data(apps, schema_editor):
    payment_status = apps.get_model('business', 'PaymentStatus')
    payment_status(title='پرداخت نشد').save()
    payment_status(title='پرداخت شد').save()


class Migration(migrations.Migration):
    dependencies = [
        ('business', '0009_auto_20190818_0723'),
    ]

    operations = [
        migrations.RunPython(seed_data),
    ]
