# Generated by Django 2.1.1 on 2019-09-24 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_auto_20190818_0723'),
    ]

    operations = [
    ]
