# Generated by Django 2.1.1 on 2019-09-29 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0010_auto_20190924_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='judgment',
            name='mablagh',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
