# Generated by Django 2.1.1 on 2019-10-05 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0011_judgment_mablagh'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('authority', models.CharField(max_length=36)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(blank=True)),
                ('ref_id', models.CharField(blank=True, max_length=100)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Dashboard')),
            ],
        ),
    ]
