# Generated by Django 2.1.1 on 2019-10-05 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0013_dashboard_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
